### ISSUE TITLE
Extracted patch features using SSL ViT-S/16 on camelyon16

### ISSUE THREAD

**Issue by abc123908** [dazhangyu123/ACMIL#1]
Hi,
    Thank you for your work. It's very amazing!
Is it possible for you to provide me with the Extracted patch features using SSL ViT-S/16 on camelyon16? I would appreciate it if you could provide it to me.
    I am looking forward to your reply!

**Comment by dazhangyu123** [comment]
We also provide Extracted patch features using SSL ViT-S/16 on camelyon16, please check the README.md.

**Comment by FabianHoerst** [comment]
Is it possible to share the used ViT-S/16 encoder? I.E, the weights or link a source if it was not trained by yourself?

**Comment by dazhangyu123** [comment]
> Is it possible to share the used ViT-S/16 encoder? I.E, the weights or link a source if it was not trained by yourself?

In the [models.py](https://github.com/dazhangyu123/ACMIL/blob/main/models.py) file, we have included a function called get_pretrained_url(key) that provides the link to the checkpoints of the pretrained encoder. You can find these checkpoints at [this location](https://github.com/lunit-io/benchmark-ssl-pathology/releases/tag/pretrained-weights).

It seems there was a mistake in replacing ViT-S/16 with ViT-B/16, and I apologize for any confusion caused by this error. I have now updated the file and corrected the mistake.

If you have any further questions or encounter any issues while running our code, please feel free to let me know. Thank you.

**Comment by FabianHoerst** [comment]
Thank you very much!
